# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43202e1a8305c89ca44fb3f177c03995ce1d8cdc784d951f668181e22d96f5871774bc387e405b47678a5e79385ac5d56485fbf60b62cf20a9effd76124aaac9

test:
  secret_key_base: 9cc27ae95aafe4251fa2e8d40575cc0baeff5dea33a3b5ee26bffb015b6b1679286a5cedbdb9c363bce4dce691860126c4b4ccff1fbf9733617b41e68c34b1b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
